FROM python:3.12-slim

# Update current packages
RUN apt-get update

# Installing git
RUN apt-get install -y git

# Configuring git
RUN git config --global core.autocrlf input
RUN git config --global user.email "simeongfremenko@gmail.com"
RUN git config --global user.name "lixelv"

# Copy requirements first to leverage Docker cache
COPY app/requirements.txt requirements.txt

# Install dependencies with caching
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application
COPY . /app

WORKDIR /app

# Installing latest version of repo
RUN git pull

