name: ${APP_NAME:-PWD##*/}

services:
    app:
        build:
            context: ..
            dockerfile: docker/Dockerfile.prod
        container_name: ${APP_NAME:-PWD##*/}
        env_file: ../.env
        environment:
            - POSTGRES_HOST=${POSTGRES_HOST:-host.docker.internal}
            - POSTGRES_PORT=${POSTGRES_PORT:-5432}
        volumes:
            - files:/docker

        restart: unless-stopped
        tty: true

volumes:
    files:
