FROM python:3.12-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Update current packages
RUN apt-get update

# Installing git
RUN apt-get install -y git

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r app/requirements.txt

# Run the bot when the container launches
CMD ["python", "app/main.py"]
