name: Deploy

on:
    push:
        branches: ["main"]
    workflow_dispatch:

jobs:
    deploy:
        runs-on: self-hosted
        environment: production

        steps:
            - uses: actions/checkout@v3
            - name: Generate .env file
              run: |
                  REPO_NAME=$(basename ${{ github.repository }}
                  echo "APP_NAME=$REPO_NAME" >> .env
                  echo "TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }}" >> .env
                  echo "POSTGRES_HOST=\"${{ secrets.POSTGRES_HOST }}\"" >> .env
                  echo "POSTGRES_PORT=\"${{ secrets.POSTGRES_PORT }}\"" >> .env
                  echo "POSTGRES_USER=\"${{ secrets.POSTGRES_USER }}\"" >> .env
                  echo "POSTGRES_PASSWORD=\"${{ secrets.POSTGRES_PASSWORD }}\"" >> .env
                  echo "POSTGRES_DB=\"${{ secrets.POSTGRES_DB }}\"" >> .env
                  echo "DEPLOY_MODE=\"${{ secrets.DEPLOY_MODE }}\"" >> .env

            - name: Build and push Docker image
              run: |
                  docker compose --env-file .env -f docker/docker-compose.$DEPLOY_MODE.yaml up -d --build
              env:
                  DEPLOY_MODE: ${{ secrets.DEPLOY_MODE }}
