name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: self-hosted

    steps:
    - name: Setup working directory
      run: |
        REPO_NAME=$(basename ${{ github.repository }})
        cd /root/github/$REPO_NAME

    - name: Get actual git repo
      run: git pull

    - name: Setup .env
      run: source .env

    - name: Build
      run: docker compose --env-file .env -f docker/docker-compose.local.yaml build

  deploy:
    runs-on: self-hosted
    steps:
      - name: Setup working directory
        run: |
          REPO_NAME=$(basename ${{ github.repository }})
          cd /root/github/$REPO_NAME
      - name: Deploy
        run: docker compose --env-file .env -f docker/docker-compose.local.yaml up -d
